cd ./2RT3RC_g12
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRTP_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCTP
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_B_g12
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_B_g12
condor_submit ./src/submit.sub
cd ..
cd ./truck2
condor_submit ./src/submit.sub
cd ..
cd ./cars2B_g12
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTCRT_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_A
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RTCRT_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCTP_g12
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRT
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RC_g23
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RTCRT
condor_submit ./src/submit.sub
cd ..
cd ./cars5_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TC_g23
condor_submit ./src/submit.sub
cd ..
cd ./articulated_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RTCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2RC_g12
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_B_g13
condor_submit ./src/submit.sub
cd ..
cd ./three-cars_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./cars3
condor_submit ./src/submit.sub
cd ..
cd ./cars2
condor_submit ./src/submit.sub
cd ..
cd ./cars2_06_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars2_06_g23
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRTP_g12
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TC_g13
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_A_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_A
condor_submit ./src/submit.sub
cd ..
cd ./people1
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCRT_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars2_07
condor_submit ./src/submit.sub
cd ..
cd ./cars2B
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCRT_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars1
condor_submit ./src/submit.sub
cd ..
cd ./1R2RC_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars7
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TC
condor_submit ./src/submit.sub
cd ..
cd ./cars2_06_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars9
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RTCRT_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars2B_g23
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars5_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars2B_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_B_g13
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_A_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_B
condor_submit ./src/submit.sub
cd ..
cd ./kanatani2
condor_submit ./src/submit.sub
cd ..
cd ./2T3RTCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_B_g23
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTCRT
condor_submit ./src/submit.sub
cd ..
cd ./kanatani1
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_B_g23
condor_submit ./src/submit.sub
cd ..
cd ./articulated_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RC_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRT_g23
condor_submit ./src/submit.sub
cd ..
cd ./cars6
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_B_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_A_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCTP_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars4
condor_submit ./src/submit.sub
cd ..
cd ./2T3RTCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_A_g13
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_A_g23
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCRT_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_B
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_B
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCR
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCR
condor_submit ./src/submit.sub
cd ..
cd ./cars10_g23
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTC_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars2_06
condor_submit ./src/submit.sub
cd ..
cd ./head
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RC
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCRT_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars2_07_g13
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_B_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2RC_g23
condor_submit ./src/submit.sub
cd ..
cd ./2T3RTCR
condor_submit ./src/submit.sub
cd ..
cd ./articulated
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_A
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_B_g23
condor_submit ./src/submit.sub
cd ..
cd ./cars10
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCR
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTC
condor_submit ./src/submit.sub
cd ..
cd ./kanatani3
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCR_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCRT
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRTP_g23
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCR_g12
condor_submit ./src/submit.sub
cd ..
cd ./two_cranes_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars5
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCRT
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_A_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars10_g12
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_A
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCTP_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TC_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars10_g13
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_B_g12
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTCRT_g13
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTCRT_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RTCRT_g23
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTC_g12
condor_submit ./src/submit.sub
cd ..
cd ./people2
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_A_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars2_07_g12
condor_submit ./src/submit.sub
cd ..
cd ./dancing
condor_submit ./src/submit.sub
cd ..
cd ./two_cranes
condor_submit ./src/submit.sub
cd ..
cd ./two_cranes_g23
condor_submit ./src/submit.sub
cd ..
cd ./cars3_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_B_g23
condor_submit ./src/submit.sub
cd ..
cd ./cars9_g23
condor_submit ./src/submit.sub
cd ..
cd ./1R2RC
condor_submit ./src/submit.sub
cd ..
cd ./three-cars_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars2_07_g23
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_A_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2TCRT_A_g13
condor_submit ./src/submit.sub
cd ..
cd ./1R2TCR
condor_submit ./src/submit.sub
cd ..
cd ./cars3_g12
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCRT_g12
condor_submit ./src/submit.sub
cd ..
cd ./arm
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRT_g12
condor_submit ./src/submit.sub
cd ..
cd ./2R3RTC_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RCRT_g23
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_A_g13
condor_submit ./src/submit.sub
cd ..
cd ./three-cars_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars8
condor_submit ./src/submit.sub
cd ..
cd ./three-cars
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCT_B
condor_submit ./src/submit.sub
cd ..
cd ./two_cranes_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars9_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars3_g23
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_A_g23
condor_submit ./src/submit.sub
cd ..
cd ./articulated_g13
condor_submit ./src/submit.sub
cd ..
cd ./truck1
condor_submit ./src/submit.sub
cd ..
cd ./1RT2RTCRT_A_g12
condor_submit ./src/submit.sub
cd ..
cd ./1R2RCR_g13
condor_submit ./src/submit.sub
cd ..
cd ./cars5_g13
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRT_g13
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCT_B_g12
condor_submit ./src/submit.sub
cd ..
cd ./cars9_g12
condor_submit ./src/submit.sub
cd ..
cd ./2RT3RCR
condor_submit ./src/submit.sub
cd ..
cd ./2T3RCRTP
condor_submit ./src/submit.sub
cd ..
